#!/usr/bin/env ruby
require_relative 'day'
class Day09 < Day
  # data is [], graph is {k => []}, f is {k => 0}, h is {}, answer,r,c,x,y are ints
  attr_accessor :h, :t, :t_hist, :s, :min_x, :max_x, :min_y, :max_y, :knots
  def part1
    # debug!
    #
    # v1, v2 = *input.split("\n\n")
    @s = Point.new(0,0)
    @knots = Array.new(10){Point.new(0,0)}
    @h = @knots.first
    @t_hist = Hash.new(0)
    @min_y = @min_x = 0
    @max_y = @max_x = 5
    # print_board "== Initial State =="

    each_line do |line, li|
      dir, steps = line.scan(/([A-Z]) (\d+)/).flatten
      steps.to_i.times do |step|
        # print "  h=#{h} t=#{t}"
        h.x += 1 if dir == 'R'
        h.x -= 1 if dir == 'L'
        h.y += 1 if dir == 'U'
        h.y -= 1 if dir == 'D'
        move_knots
        # print_board "== #{line} =="
        t_hist[@knots.last.to_s] += 1
      end
    end
    self.answer = t_hist.size
    puts "\n\nAnswer is #{answer}"
    # submit_answer(part: 1, answer: answer) unless ARGV.join.include?('.ex')
  end

  def print_board(banner)
    clear_lines(4+max_y-min_y)
    puts "#{banner}\n"
    @min_x = [min_x, *@knots.map(&:x)].compact.min
    @max_x = [max_x, *@knots.map(&:x)].compact.max
    @min_y = [min_y, *@knots.map(&:y)].compact.min
    @max_y = [max_y, *@knots.map(&:y)].compact.max
    max_y.downto(min_y) do |y|
      min_x.upto(max_x) do |x|
        if h.x == x && h.y == y
          print 'H'
        elsif (ti = @knots[1..-1].index{|k| k.x == x && k.y == y})
          print ti+1
        elsif s.x == x && s.y == y
          print 's'
        else
          print '.'
        end
      end
      puts
    end
    puts "\n"
  end

  def move_knots
    1.upto(@knots.size-1) do |ki|
      t = @knots[ki]
      trapped = 0.upto(ki-1).any? do |ki2|
        k2 = @knots[ki2]
        t.dist(k2) <= 2 ** 0.5
      end
      next if trapped

      h = @knots[ki-1]
      if t.x == h.x
        # move vertically
        if h.y > t.y + 1
          t.y += 1
        elsif h.y < t.y - 1
          t.y -= 1
        end
      elsif t.y == h.y
        # move horizontally
        if h.x > t.x + 1
          t.x += 1
        elsif h.x < t.x - 1
          t.x -= 1
        end
      else
        # move diagonally
        if h.x > t.x
          t.x += 1
        elsif h.x < t.x
          t.x -= 1
        end
        if h.y > t.y
          t.y += 1
        elsif h.y < t.y
          t.y -= 1
        end
      end

    end
  end
  # def part2
  #   # debug!
  #   puts "Answer is #{answer}"
  #   submit_answer(part: 2, answer: answer) unless ARGV.join.include?('.ex')
  # end
end
if __FILE__ == $0
  ENV["INPUT"] = ARGV.last || __FILE__.split("/").last.gsub(".rb",'')
  d = Day09.new
  d.respond_to?(:part2) ? d.part2 : d.part1
end

=begin
## --- Day 9: Rope Bridge ---This rope bridge creaks as you walk along it. You aren't sure how old it is, or whether it can even support your weight.

It seems to support the Elves just fine, though. The bridge spans a gorge which was carved out by the massive river far below you.

You step carefully; as you do, the ropes stretch and twist. You decide to distract yourself by modeling rope physics; maybe you can even figure out where *not* to step.

Consider a rope with a knot at each end; these knots mark the *head* and the *tail* of the rope. If the head moves far enough away from the tail, the tail is pulled toward the head.

Due to nebulous reasoning involving [Planck lengths](https://en.wikipedia.org/wiki/Planck_units#Planck_length ""), you should be able to model the positions of the knots on a two-dimensional grid. Then, by following a hypothetical *series of motions* (your puzzle input) for the head, you can determine how the tail will move.

Due to the aforementioned Planck lengths, the rope must be quite short; in fact, the head (`H`) and tail (`T`) must *always be touching* (diagonally adjacent and even overlapping both count as touching):

```
....
.TH.
....

....
.H..
..T.
....

...
.H. (H covers T)
...
```

If the head is ever two steps directly up, down, left, or right from the tail, the tail must also move one step in that direction so it remains close enough:

```
.....    .....    .....
.TH.. -> .T.H. -> ..TH.
.....    .....    .....

...    ...    ...
.T.    .T.    ...
.H. -> ... -> .T.
...    .H.    .H.
...    ...    ...
```

Otherwise, if the head and tail aren't touching and aren't in the same row or column, the tail always moves one step diagonally to keep up:

```
.....    .....    .....
.....    ..H..    ..H..
..H.. -> ..... -> ..T..
.T...    .T...    .....
.....    .....    .....

.....    .....    .....
.....    .....    .....
..H.. -> ...H. -> ..TH.
.T...    .T...    .....
.....    .....    .....
```

You just need to work out where the tail goes as the head follows a series of motions. Assume the head and the tail both start at the same position, overlapping.

For example:

```
R 4
U 4
L 3
D 1
R 4
D 1
L 5
R 2
```

This series of motions moves the head *right* four steps, then *up* four steps, then *left* three steps, then *down* one step, and so on. After each step, you'll need to update the position of the tail if the step means the head is no longer adjacent to the tail. Visually, these motions occur as follows (`s` marks the starting position as a reference point):

```
== Initial State ==

......
......
......
......
H.....  (H covers T, s)

== R 4 ==

......
......
......
......
TH....  (T covers s)

......
......
......
......
sTH...

......
......
......
......
s.TH..

......
......
......
......
s..TH.

== U 4 ==

......
......
......
....H.
s..T..

......
......
....H.
....T.
s.....

......
....H.
....T.
......
s.....

....H.
....T.
......
......
s.....

== L 3 ==

...H..
....T.
......
......
s.....

..HT..
......
......
......
s.....

.HT...
......
......
......
s.....

== D 1 ==

..T...
.H....
......
......
s.....

== R 4 ==

..T...
..H...
......
......
s.....

..T...
...H..
......
......
s.....

......
...TH.
......
......
s.....

......
....TH
......
......
s.....

== D 1 ==

......
....T.
.....H
......
s.....

== L 5 ==

......
....T.
....H.
......
s.....

......
....T.
...H..
......
s.....

......
......
..HT..
......
s.....

......
......
.HT...
......
s.....

......
......
HT....
......
s.....

== R 2 ==

......
......
.H....  (H covers T)
......
s.....

......
......
.TH...
......
s.....
```

After simulating the rope, you can count up all of the positions the *tail visited at least once*. In this diagram, `s` again marks the starting position (which the tail also visited) and `#` marks other positions the tail visited:

```
..##..
...##.
.####.
....#.
s###..
```

So, there are `*13*` positions the tail visited at least once.

Simulate your complete hypothetical series of motions. *How many positions does the tail of the rope visit at least once?*
=end
